[system]
compatible=omnios-x86-64
min-bundle-version=@OMNIOS_BUNDLE_VERSION@
bootloader=grub
grubenv=/grubenv/grubenv
data-directory=/data/rauc
mountprefix=/run/rauc
activate-installed=true

[keyring]
path=ca.cert.pem

[slot.rootfs.0]
device=/dev/disk/by-partlabel/omnios-root-a
type=ext4
bootname=A

[slot.rootfs.1]
device=/dev/disk/by-partlabel/omnios-root-b
type=ext4
bootname=B
