BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb ${LAYERDIR}/recipes-*/*/*.bbappend"
BBFILE_COLLECTIONS += "omnios"
BBFILE_PATTERN_omnios = "^${LAYERDIR}/"
BBFILE_PRIORITY_omnios = "10"
LAYERDEPENDS_omnios = "core openembedded-layer networking-layer multimedia-layer meta-python filesystems-layer perl-layer qt6-layer kf6 kde rauc"
LAYERSERIES_COMPAT_omnios = "wrynose"
