#!/bin/sh
set -eu

ROOT=$(CDPATH='' cd -- "$(dirname -- "$0")/.." && pwd)
VERSION=$(tr -d '[:space:]' < "$ROOT/version.txt")
printf '%s' "$VERSION" | grep -Eq '^[0-9]{4}\.[0-9]+(\.[0-9]+)?$' || {
    echo 'ERROR: invalid OmniOS version in version.txt' >&2
    exit 1
}

lb config noauto \
    --mode debian \
    --system live \
    --distribution trixie \
    --architecture amd64 \
    --linux-flavours amd64 \
    --archive-areas "main contrib non-free-firmware" \
    --parent-archive-areas "main contrib non-free-firmware" \
    --mirror-bootstrap "https://deb.debian.org/debian/" \
    --mirror-chroot "https://deb.debian.org/debian/" \
    --mirror-binary "https://deb.debian.org/debian/" \
    --mirror-chroot-security "https://security.debian.org/debian-security/" \
    --mirror-binary-security "https://security.debian.org/debian-security/" \
    --security true \
    --updates true \
    --backports false \
    --apt-recommends true \
    --apt-secure true \
    --binary-image iso-hybrid \
    --bootloaders "syslinux grub-efi" \
    --debian-installer none \
    --firmware-binary true \
    --firmware-chroot true \
    --chroot-filesystem squashfs \
    --chroot-squashfs-compression-type zstd \
    --chroot-squashfs-compression-level 6 \
    --uefi-secure-boot auto \
    --checksums sha256 \
    --source false \
    --image-name omnios \
    --iso-application "OmniOS Desktop" \
    --iso-publisher "OmniNodeCo; https://github.com/OmniNodeCo/OmniOS" \
    --iso-volume "OmniOS $VERSION amd64" \
    --bootappend-live "boot=live components quiet splash username=omnios hostname=omnios locales=en_US.UTF-8 keyboard-layouts=us timezone=Etc/UTC console=ttyS0,115200 console=tty0" \
    "$@"
