---
efiSystemPartition: "/boot/efi"
userSwapChoices:
    - none
    - small
    - suspend
    - file
initialPartitioningChoice: none
initialSwapChoice: none
allowManualPartitioning: true
drawNestedPartitions: true
alwaysShowPartitionLabels: true
defaultFileSystemType: "btrfs"
availableFileSystemTypes: ["btrfs", "ext4"]
