#!/bin/bash
set -Eeuo pipefail

install -d -m 0755 /var/lib/omnios
flatpak remote-add --system --if-not-exists flathub \
    https://dl.flathub.org/repo/flathub.flatpakrepo
touch /var/lib/omnios/flathub-configured
