SUMMARY = "Signed OmniOS x86-64 A/B system update bundle"
LICENSE = "MIT"
LIC_FILES_CHKSUM = "file://${COMMON_LICENSE_DIR}/MIT;md5=0835ade698e0bcf8506ecda2f7b4f302"
SRC_URI = "file://omnios-bundle-hook"
inherit bundle
RAUC_BUNDLE_COMPATIBLE = "omnios-x86-64"
RAUC_BUNDLE_VERSION = "${OMNIOS_BUNDLE_VERSION}"
RAUC_BUNDLE_DESCRIPTION = "OmniOS ${DISTRO_VERSION} Plasma system update"
RAUC_BUNDLE_FORMAT = "verity"
RAUC_BUNDLE_SLOTS = "rootfs"
RAUC_SLOT_rootfs = "omnios-plasma-image"
RAUC_SLOT_rootfs[fstype] = "ext4"
RAUC_SLOT_rootfs[hooks] = "post-install"
RAUC_BUNDLE_HOOKS[file] = "omnios-bundle-hook"
